name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Verify
        run: mvn clean verify

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./contacts-service/Dockerfile
          push: false
          tags: erikrz/contacts-service:pr-${{ github.event.pull_request.number }}
